upstream django_api {
    server api:8000;
}

server {
    listen 80;
    server_name localhost;

    # Limite de taille de transfert de fichiers si besoin (ex: uploads)
    client_max_body_size 20M;

    # Servir les fichiers statiques de Django (Admin DRF, Swagger UI, etc.)
    location /static/ {
        alias /app/staticfiles/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Redirection de toutes les requêtes vers l'API Django (Gunicorn)
    location / {
        proxy_pass http://django_api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Délais d'expiration (Timeouts)
        proxy_connect_timeout 60s;
        proxy_read_timeout 60s;
    }
}
